default_language_version:
    python: python3.12

default_stages: [commit, push]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-added-large-files
          - id: check-yaml
          - id: check-toml
          - id: end-of-file-fixer
            exclude: LICENSE

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.6.4
      hooks:
        - id: ruff
          args: [ --fix ]
        - id: ruff-format

    -   repo: https://github.com/Yelp/detect-secrets
        rev: v1.5.0
        hooks:
        -   id: detect-secrets
            args: ['--baseline', '.secrets.baseline']
            exclude: 'poetry.lock|opennem/db/migrations/versions/.*\.py|tests/.*\.py'

    # - repo: https://github.com/RobertCraigie/pyright-python
    #   rev: v1.1.295
    #   hooks:
    #     - id: pyright
